pruebas_index:
  path: /pruebas/{lang}/{name}/{page}
  defaults: { _controller: AppBundle:Pruebas:index,lang:es ,name:Gonzalo, page:contenido_por_defecto }
  methods: [GET]
  requirements:
      name: "[a-zA-Z]*"
      page: \d+
      lang: es|en|fr
